version: "2"

run:
  timeout: 3m

linters:
  enable:
    - staticcheck
    - errcheck
    - unused
    - ineffassign
  exclusions:
    paths:
      - internal/infra/postgres/sqlc

formatters:
  enable:
    - gofmt
