// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT
  u.id, u.email, u.full_name, u.email_verified_at, u.created_at,
  o.id AS organization_id, o.name AS organization_name,
  o.commission_rate AS organization_commission_rate,
  COUNT(c.id) AS campaign_count
FROM users u
JOIN organization_members om ON om.user_id = u.id AND om.role = 'owner'
JOIN organizations o ON o.id = om.organization_id
LEFT JOIN campaigns c ON c.organization_id = o.id AND c.deleted_at IS NULL
GROUP BY u.id, o.id
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAdminUsersRow struct {
	ID                         uuid.UUID          `json:"id"`
	Email                      string             `json:"email"`
	FullName                   string             `json:"full_name"`
	EmailVerifiedAt            pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	OrganizationID             uuid.UUID          `json:"organization_id"`
	OrganizationName           string             `json:"organization_name"`
	OrganizationCommissionRate pgtype.Numeric     `json:"organization_commission_rate"`
	CampaignCount              int64              `json:"campaign_count"`
}

func (q *Queries) ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]ListAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminUsersRow
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.OrganizationCommissionRate,
			&i.CampaignCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminCampaigns = `-- name: ListAdminCampaigns :many
SELECT
  c.id, c.title, c.slug, c.type_key, c.status, c.category, c.created_at,
  o.name AS organization_name, u.email AS organizer_email,
  COALESCE(ct.raised_gross, 0)::bigint AS raised_gross,
  COALESCE(ct.contributor_count, 0)::bigint AS contributor_count
FROM campaigns c
JOIN organizations o ON o.id = c.organization_id
JOIN organization_members om ON om.organization_id = o.id AND om.role = 'owner'
JOIN users u ON u.id = om.user_id
LEFT JOIN campaign_totals ct ON ct.campaign_id = c.id
WHERE c.deleted_at IS NULL
ORDER BY c.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminCampaignsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAdminCampaignsRow struct {
	ID               uuid.UUID          `json:"id"`
	Title            string             `json:"title"`
	Slug             string             `json:"slug"`
	TypeKey          string             `json:"type_key"`
	Status           string             `json:"status"`
	Category         string             `json:"category"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	OrganizationName string             `json:"organization_name"`
	OrganizerEmail   string             `json:"organizer_email"`
	RaisedGross      int64              `json:"raised_gross"`
	ContributorCount int64              `json:"contributor_count"`
}

func (q *Queries) ListAdminCampaigns(ctx context.Context, arg ListAdminCampaignsParams) ([]ListAdminCampaignsRow, error) {
	rows, err := q.db.Query(ctx, listAdminCampaigns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminCampaignsRow
	for rows.Next() {
		var i ListAdminCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.TypeKey,
			&i.Status,
			&i.Category,
			&i.CreatedAt,
			&i.OrganizationName,
			&i.OrganizerEmail,
			&i.RaisedGross,
			&i.ContributorCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminPayments = `-- name: ListAdminPayments :many
SELECT
  p.id, p.status, p.provider, p.amount_gross, p.amount_net, p.commission_amount,
  p.created_at, p.confirmed_at,
  c.title AS campaign_title, c.slug AS campaign_slug,
  ctr.full_name AS contributor_name
FROM payments p
JOIN contributions co ON co.id = p.contribution_id
JOIN campaigns c ON c.id = co.campaign_id
JOIN contributors ctr ON ctr.id = co.contributor_id
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminPaymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAdminPaymentsRow struct {
	ID               uuid.UUID          `json:"id"`
	Status           string             `json:"status"`
	Provider         string             `json:"provider"`
	AmountGross      int64              `json:"amount_gross"`
	AmountNet        int64              `json:"amount_net"`
	CommissionAmount int64              `json:"commission_amount"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ConfirmedAt      pgtype.Timestamptz `json:"confirmed_at"`
	CampaignTitle    string             `json:"campaign_title"`
	CampaignSlug     string             `json:"campaign_slug"`
	ContributorName  string             `json:"contributor_name"`
}

func (q *Queries) ListAdminPayments(ctx context.Context, arg ListAdminPaymentsParams) ([]ListAdminPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listAdminPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminPaymentsRow
	for rows.Next() {
		var i ListAdminPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Provider,
			&i.AmountGross,
			&i.AmountNet,
			&i.CommissionAmount,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.CampaignTitle,
			&i.CampaignSlug,
			&i.ContributorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminMetrics = `-- name: GetAdminMetrics :one
SELECT
  (SELECT COUNT(*) FROM users)::bigint AS total_users,
  (SELECT COUNT(*) FROM campaigns WHERE deleted_at IS NULL)::bigint AS total_campaigns,
  (SELECT COUNT(*) FROM campaigns WHERE status = 'active' AND deleted_at IS NULL)::bigint AS active_campaigns,
  (SELECT COUNT(*) FROM campaigns WHERE status = 'draft' AND deleted_at IS NULL)::bigint AS draft_campaigns,
  (SELECT COUNT(*) FROM campaigns WHERE status = 'finished' AND deleted_at IS NULL)::bigint AS finished_campaigns,
  (SELECT COUNT(*) FROM contributions WHERE status = 'confirmed')::bigint AS total_contributions,
  (SELECT COALESCE(SUM(raised_gross), 0)::bigint FROM campaign_totals) AS raised_gross,
  (SELECT COALESCE(SUM(raised_net_approx), 0)::bigint FROM campaign_totals) AS raised_net_approx,
  (SELECT COALESCE(SUM(commission_amount), 0)::bigint FROM payments WHERE status = 'confirmed') AS total_commission
`

type GetAdminMetricsRow struct {
	TotalUsers         int64 `json:"total_users"`
	TotalCampaigns     int64 `json:"total_campaigns"`
	ActiveCampaigns    int64 `json:"active_campaigns"`
	DraftCampaigns     int64 `json:"draft_campaigns"`
	FinishedCampaigns  int64 `json:"finished_campaigns"`
	TotalContributions int64 `json:"total_contributions"`
	RaisedGross        int64 `json:"raised_gross"`
	RaisedNetApprox    int64 `json:"raised_net_approx"`
	TotalCommission    int64 `json:"total_commission"`
}

func (q *Queries) GetAdminMetrics(ctx context.Context) (GetAdminMetricsRow, error) {
	row := q.db.QueryRow(ctx, getAdminMetrics)
	var i GetAdminMetricsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.TotalCampaigns,
		&i.ActiveCampaigns,
		&i.DraftCampaigns,
		&i.FinishedCampaigns,
		&i.TotalContributions,
		&i.RaisedGross,
		&i.RaisedNetApprox,
		&i.TotalCommission,
	)
	return i, err
}
