// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (actor_user_id, organization_id, action, entity_type, entity_id, data)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuditLogParams struct {
	ActorUserID    pgtype.UUID `json:"actor_user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Action         string      `json:"action"`
	EntityType     string      `json:"entity_type"`
	EntityID       uuid.UUID   `json:"entity_id"`
	Data           []byte      `json:"data"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ActorUserID,
		arg.OrganizationID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Data,
	)
	return err
}
