// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaign_images.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const nextCampaignImagePosition = `-- name: NextCampaignImagePosition :one
SELECT COALESCE(MAX(position) + 1, 0)::int FROM campaign_images WHERE campaign_id = $1
`

func (q *Queries) NextCampaignImagePosition(ctx context.Context, campaignID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextCampaignImagePosition, campaignID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createCampaignImage = `-- name: CreateCampaignImage :one
INSERT INTO campaign_images (campaign_id, file_id, position)
VALUES ($1, $2, $3)
RETURNING id, campaign_id, file_id, position, created_at
`

type CreateCampaignImageParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	FileID     uuid.UUID `json:"file_id"`
	Position   int32     `json:"position"`
}

func (q *Queries) CreateCampaignImage(ctx context.Context, arg CreateCampaignImageParams) (CampaignImage, error) {
	row := q.db.QueryRow(ctx, createCampaignImage, arg.CampaignID, arg.FileID, arg.Position)
	var i CampaignImage
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.FileID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listCampaignImages = `-- name: ListCampaignImages :many
SELECT ci.id, ci.position, f.storage_key
FROM campaign_images ci
JOIN files f ON f.id = ci.file_id
WHERE ci.campaign_id = $1
ORDER BY ci.position ASC
`

type ListCampaignImagesRow struct {
	ID         uuid.UUID `json:"id"`
	Position   int32     `json:"position"`
	StorageKey string    `json:"storage_key"`
}

func (q *Queries) ListCampaignImages(ctx context.Context, campaignID uuid.UUID) ([]ListCampaignImagesRow, error) {
	rows, err := q.db.Query(ctx, listCampaignImages, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignImagesRow
	for rows.Next() {
		var i ListCampaignImagesRow
		if err := rows.Scan(&i.ID, &i.Position, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCampaignImage = `-- name: DeleteCampaignImage :execrows
DELETE FROM campaign_images WHERE id = $1 AND campaign_id = $2
`

type DeleteCampaignImageParams struct {
	ID         uuid.UUID `json:"id"`
	CampaignID uuid.UUID `json:"campaign_id"`
}

func (q *Queries) DeleteCampaignImage(ctx context.Context, arg DeleteCampaignImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCampaignImage, arg.ID, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
