// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (organization_id, type_key, title, slug, description, goal_amount, starts_at, ends_at, publish_at, category, video_url, raffle_unit_price, raffle_total_numbers)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, organization_id, type_key, title, slug, description, cover_file_id, goal_amount, currency, status, starts_at, ends_at, settings, deleted_at, created_at, updated_at, publish_at, category, video_url, raffle_unit_price, raffle_total_numbers, raffle_winning_number
`

type CreateCampaignParams struct {
	OrganizationID     uuid.UUID          `json:"organization_id"`
	TypeKey            string             `json:"type_key"`
	Title              string             `json:"title"`
	Slug               string             `json:"slug"`
	Description        string             `json:"description"`
	GoalAmount         pgtype.Int8        `json:"goal_amount"`
	StartsAt           pgtype.Timestamptz `json:"starts_at"`
	EndsAt             pgtype.Timestamptz `json:"ends_at"`
	PublishAt          pgtype.Timestamptz `json:"publish_at"`
	Category           string             `json:"category"`
	VideoUrl           pgtype.Text        `json:"video_url"`
	RaffleUnitPrice    pgtype.Int8        `json:"raffle_unit_price"`
	RaffleTotalNumbers pgtype.Int4        `json:"raffle_total_numbers"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.OrganizationID,
		arg.TypeKey,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.GoalAmount,
		arg.StartsAt,
		arg.EndsAt,
		arg.PublishAt,
		arg.Category,
		arg.VideoUrl,
		arg.RaffleUnitPrice,
		arg.RaffleTotalNumbers,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TypeKey,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverFileID,
		&i.GoalAmount,
		&i.Currency,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Settings,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishAt,
		&i.Category,
		&i.VideoUrl,
		&i.RaffleUnitPrice,
		&i.RaffleTotalNumbers,
		&i.RaffleWinningNumber,
	)
	return i, err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, organization_id, type_key, title, slug, description, cover_file_id, goal_amount, currency, status, starts_at, ends_at, settings, deleted_at, created_at, updated_at, publish_at, category, video_url, raffle_unit_price, raffle_total_numbers, raffle_winning_number FROM campaigns WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCampaignByID(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TypeKey,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverFileID,
		&i.GoalAmount,
		&i.Currency,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Settings,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishAt,
		&i.Category,
		&i.VideoUrl,
		&i.RaffleUnitPrice,
		&i.RaffleTotalNumbers,
		&i.RaffleWinningNumber,
	)
	return i, err
}

const getCampaignByIDForOrg = `-- name: GetCampaignByIDForOrg :one
SELECT id, organization_id, type_key, title, slug, description, cover_file_id, goal_amount, currency, status, starts_at, ends_at, settings, deleted_at, created_at, updated_at, publish_at, category, video_url, raffle_unit_price, raffle_total_numbers, raffle_winning_number FROM campaigns WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetCampaignByIDForOrgParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetCampaignByIDForOrg(ctx context.Context, arg GetCampaignByIDForOrgParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByIDForOrg, arg.ID, arg.OrganizationID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TypeKey,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverFileID,
		&i.GoalAmount,
		&i.Currency,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Settings,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishAt,
		&i.Category,
		&i.VideoUrl,
		&i.RaffleUnitPrice,
		&i.RaffleTotalNumbers,
		&i.RaffleWinningNumber,
	)
	return i, err
}

const getCampaignBySlug = `-- name: GetCampaignBySlug :one
SELECT id, organization_id, type_key, title, slug, description, cover_file_id, goal_amount, currency, status, starts_at, ends_at, settings, deleted_at, created_at, updated_at, publish_at, category, video_url, raffle_unit_price, raffle_total_numbers, raffle_winning_number FROM campaigns WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCampaignBySlug(ctx context.Context, slug string) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignBySlug, slug)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TypeKey,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverFileID,
		&i.GoalAmount,
		&i.Currency,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Settings,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishAt,
		&i.Category,
		&i.VideoUrl,
		&i.RaffleUnitPrice,
		&i.RaffleTotalNumbers,
		&i.RaffleWinningNumber,
	)
	return i, err
}

const getCampaignTotals = `-- name: GetCampaignTotals :one
SELECT campaign_id, raised_gross, raised_net_approx, contributor_count FROM campaign_totals WHERE campaign_id = $1
`

func (q *Queries) GetCampaignTotals(ctx context.Context, campaignID uuid.UUID) (CampaignTotal, error) {
	row := q.db.QueryRow(ctx, getCampaignTotals, campaignID)
	var i CampaignTotal
	err := row.Scan(
		&i.CampaignID,
		&i.RaisedGross,
		&i.RaisedNetApprox,
		&i.ContributorCount,
	)
	return i, err
}

const getFeaturedCampaign = `-- name: GetFeaturedCampaign :one
SELECT c.id, c.organization_id, c.type_key, c.title, c.slug, c.description, c.cover_file_id, c.goal_amount, c.currency, c.status, c.starts_at, c.ends_at, c.settings, c.deleted_at, c.created_at, c.updated_at, c.publish_at, c.category, c.video_url, c.raffle_unit_price, c.raffle_total_numbers, c.raffle_winning_number FROM campaigns c
JOIN contributions ct ON ct.campaign_id = c.id
JOIN payments p ON p.contribution_id = ct.id
WHERE c.status = 'active' AND c.deleted_at IS NULL AND p.status = 'confirmed'
ORDER BY p.confirmed_at DESC
LIMIT 1
`

func (q *Queries) GetFeaturedCampaign(ctx context.Context) (Campaign, error) {
	row := q.db.QueryRow(ctx, getFeaturedCampaign)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TypeKey,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverFileID,
		&i.GoalAmount,
		&i.Currency,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Settings,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishAt,
		&i.Category,
		&i.VideoUrl,
		&i.RaffleUnitPrice,
		&i.RaffleTotalNumbers,
		&i.RaffleWinningNumber,
	)
	return i, err
}

const listCampaignsByOrg = `-- name: ListCampaignsByOrg :many
SELECT id, organization_id, type_key, title, slug, description, cover_file_id, goal_amount, currency, status, starts_at, ends_at, settings, deleted_at, created_at, updated_at, publish_at, category, video_url, raffle_unit_price, raffle_total_numbers, raffle_winning_number FROM campaigns
WHERE organization_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCampaignsByOrgParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListCampaignsByOrg(ctx context.Context, arg ListCampaignsByOrgParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByOrg, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TypeKey,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverFileID,
			&i.GoalAmount,
			&i.Currency,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.Settings,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishAt,
			&i.Category,
			&i.VideoUrl,
			&i.RaffleUnitPrice,
			&i.RaffleTotalNumbers,
			&i.RaffleWinningNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicCampaignsByOrg = `-- name: ListPublicCampaignsByOrg :many
SELECT id, organization_id, type_key, title, slug, description, cover_file_id, goal_amount, currency, status, starts_at, ends_at, settings, deleted_at, created_at, updated_at, publish_at, category, video_url, raffle_unit_price, raffle_total_numbers, raffle_winning_number FROM campaigns
WHERE organization_id = $1 AND deleted_at IS NULL
  AND status IN ('active', 'paused', 'finished')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublicCampaignsByOrgParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListPublicCampaignsByOrg(ctx context.Context, arg ListPublicCampaignsByOrgParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listPublicCampaignsByOrg, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TypeKey,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverFileID,
			&i.GoalAmount,
			&i.Currency,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.Settings,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishAt,
			&i.Category,
			&i.VideoUrl,
			&i.RaffleUnitPrice,
			&i.RaffleTotalNumbers,
			&i.RaffleWinningNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveCampaigns = `-- name: ListActiveCampaigns :many
SELECT id, organization_id, type_key, title, slug, description, cover_file_id, goal_amount, currency, status, starts_at, ends_at, settings, deleted_at, created_at, updated_at, publish_at, category, video_url, raffle_unit_price, raffle_total_numbers, raffle_winning_number FROM campaigns
WHERE status = 'active' AND deleted_at IS NULL
  AND ($3::text IS NULL OR title ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR category = $4)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveCampaignsParams struct {
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Search   pgtype.Text `json:"search"`
	Category pgtype.Text `json:"category"`
}

func (q *Queries) ListActiveCampaigns(ctx context.Context, arg ListActiveCampaignsParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listActiveCampaigns,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TypeKey,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverFileID,
			&i.GoalAmount,
			&i.Currency,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.Settings,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishAt,
			&i.Category,
			&i.VideoUrl,
			&i.RaffleUnitPrice,
			&i.RaffleTotalNumbers,
			&i.RaffleWinningNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishDueCampaigns = `-- name: PublishDueCampaigns :many
UPDATE campaigns SET status = 'active', publish_at = NULL, updated_at = now()
WHERE status = 'draft' AND publish_at IS NOT NULL AND publish_at <= now() AND deleted_at IS NULL
RETURNING id, organization_id, type_key, title, slug, description, cover_file_id, goal_amount, currency, status, starts_at, ends_at, settings, deleted_at, created_at, updated_at, publish_at, category, video_url, raffle_unit_price, raffle_total_numbers, raffle_winning_number
`

func (q *Queries) PublishDueCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, publishDueCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TypeKey,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CoverFileID,
			&i.GoalAmount,
			&i.Currency,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.Settings,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishAt,
			&i.Category,
			&i.VideoUrl,
			&i.RaffleUnitPrice,
			&i.RaffleTotalNumbers,
			&i.RaffleWinningNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS(SELECT 1 FROM campaigns WHERE slug = $1)
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteCampaign = `-- name: SoftDeleteCampaign :exec
UPDATE campaigns SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteCampaign(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCampaign, id)
	return err
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns SET
  title = $2,
  description = $3,
  goal_amount = $4,
  starts_at = $5,
  ends_at = $6,
  cover_file_id = $7,
  publish_at = $8,
  category = $9,
  video_url = $10,
  raffle_unit_price = $11,
  raffle_total_numbers = $12,
  raffle_winning_number = $13,
  updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, type_key, title, slug, description, cover_file_id, goal_amount, currency, status, starts_at, ends_at, settings, deleted_at, created_at, updated_at, publish_at, category, video_url, raffle_unit_price, raffle_total_numbers, raffle_winning_number
`

type UpdateCampaignParams struct {
	ID                  uuid.UUID          `json:"id"`
	Title               string             `json:"title"`
	Description         string             `json:"description"`
	GoalAmount          pgtype.Int8        `json:"goal_amount"`
	StartsAt            pgtype.Timestamptz `json:"starts_at"`
	EndsAt              pgtype.Timestamptz `json:"ends_at"`
	CoverFileID         pgtype.UUID        `json:"cover_file_id"`
	PublishAt           pgtype.Timestamptz `json:"publish_at"`
	Category            string             `json:"category"`
	VideoUrl            pgtype.Text        `json:"video_url"`
	RaffleUnitPrice     pgtype.Int8        `json:"raffle_unit_price"`
	RaffleTotalNumbers  pgtype.Int4        `json:"raffle_total_numbers"`
	RaffleWinningNumber pgtype.Int4        `json:"raffle_winning_number"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.GoalAmount,
		arg.StartsAt,
		arg.EndsAt,
		arg.CoverFileID,
		arg.PublishAt,
		arg.Category,
		arg.VideoUrl,
		arg.RaffleUnitPrice,
		arg.RaffleTotalNumbers,
		arg.RaffleWinningNumber,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TypeKey,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverFileID,
		&i.GoalAmount,
		&i.Currency,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Settings,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishAt,
		&i.Category,
		&i.VideoUrl,
		&i.RaffleUnitPrice,
		&i.RaffleTotalNumbers,
		&i.RaffleWinningNumber,
	)
	return i, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE campaigns SET status = $2, publish_at = NULL, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, type_key, title, slug, description, cover_file_id, goal_amount, currency, status, starts_at, ends_at, settings, deleted_at, created_at, updated_at, publish_at, category, video_url, raffle_unit_price, raffle_total_numbers, raffle_winning_number
`

type UpdateCampaignStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignStatus, arg.ID, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TypeKey,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CoverFileID,
		&i.GoalAmount,
		&i.Currency,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Settings,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishAt,
		&i.Category,
		&i.VideoUrl,
		&i.RaffleUnitPrice,
		&i.RaffleTotalNumbers,
		&i.RaffleWinningNumber,
	)
	return i, err
}
