// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contributors.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContributor = `-- name: CreateContributor :one
INSERT INTO contributors (full_name, email, phone)
VALUES ($1, $2, $3)
RETURNING id, full_name, email, phone, created_at
`

type CreateContributorParams struct {
	FullName string      `json:"full_name"`
	Email    pgtype.Text `json:"email"`
	Phone    pgtype.Text `json:"phone"`
}

func (q *Queries) CreateContributor(ctx context.Context, arg CreateContributorParams) (Contributor, error) {
	row := q.db.QueryRow(ctx, createContributor, arg.FullName, arg.Email, arg.Phone)
	var i Contributor
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}
