// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contributions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContribution = `-- name: CreateContribution :one
INSERT INTO contributions (campaign_id, contributor_id, amount, is_anonymous, message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, campaign_id, contributor_id, amount, currency, is_anonymous, message, status, created_at, updated_at
`

type CreateContributionParams struct {
	CampaignID    uuid.UUID   `json:"campaign_id"`
	ContributorID uuid.UUID   `json:"contributor_id"`
	Amount        int64       `json:"amount"`
	IsAnonymous   bool        `json:"is_anonymous"`
	Message       pgtype.Text `json:"message"`
}

func (q *Queries) CreateContribution(ctx context.Context, arg CreateContributionParams) (Contribution, error) {
	row := q.db.QueryRow(ctx, createContribution,
		arg.CampaignID,
		arg.ContributorID,
		arg.Amount,
		arg.IsAnonymous,
		arg.Message,
	)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContributorID,
		&i.Amount,
		&i.Currency,
		&i.IsAnonymous,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContributionByID = `-- name: GetContributionByID :one
SELECT id, campaign_id, contributor_id, amount, currency, is_anonymous, message, status, created_at, updated_at FROM contributions WHERE id = $1
`

func (q *Queries) GetContributionByID(ctx context.Context, id uuid.UUID) (Contribution, error) {
	row := q.db.QueryRow(ctx, getContributionByID, id)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContributorID,
		&i.Amount,
		&i.Currency,
		&i.IsAnonymous,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContributionsByCampaign = `-- name: ListContributionsByCampaign :many
SELECT id, campaign_id, contributor_id, amount, currency, is_anonymous, message, status, created_at, updated_at FROM contributions
WHERE campaign_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListContributionsByCampaignParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListContributionsByCampaign(ctx context.Context, arg ListContributionsByCampaignParams) ([]Contribution, error) {
	rows, err := q.db.Query(ctx, listContributionsByCampaign, arg.CampaignID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contribution
	for rows.Next() {
		var i Contribution
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ContributorID,
			&i.Amount,
			&i.Currency,
			&i.IsAnonymous,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsByCampaign = `-- name: ListParticipantsByCampaign :many
SELECT
  c.id AS contribution_id,
  ct.full_name AS contributor_full_name,
  ct.email AS contributor_email,
  ct.phone AS contributor_phone,
  c.amount,
  COALESCE(r.refunded, 0)::bigint AS refunded_amount,
  c.is_anonymous,
  c.status,
  c.created_at
FROM contributions c
JOIN contributors ct ON ct.id = c.contributor_id
LEFT JOIN payments p ON p.contribution_id = c.id
LEFT JOIN LATERAL (
  SELECT SUM(pr.amount) AS refunded FROM payment_refunds pr WHERE pr.payment_id = p.id
) r ON true
WHERE c.campaign_id = $1
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type ListParticipantsByCampaignParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type ListParticipantsByCampaignRow struct {
	ContributionID      uuid.UUID          `json:"contribution_id"`
	ContributorFullName string             `json:"contributor_full_name"`
	ContributorEmail    pgtype.Text        `json:"contributor_email"`
	ContributorPhone    pgtype.Text        `json:"contributor_phone"`
	Amount              int64              `json:"amount"`
	RefundedAmount      int64              `json:"refunded_amount"`
	IsAnonymous         bool               `json:"is_anonymous"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListParticipantsByCampaign(ctx context.Context, arg ListParticipantsByCampaignParams) ([]ListParticipantsByCampaignRow, error) {
	rows, err := q.db.Query(ctx, listParticipantsByCampaign, arg.CampaignID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantsByCampaignRow
	for rows.Next() {
		var i ListParticipantsByCampaignRow
		if err := rows.Scan(
			&i.ContributionID,
			&i.ContributorFullName,
			&i.ContributorEmail,
			&i.ContributorPhone,
			&i.Amount,
			&i.RefundedAmount,
			&i.IsAnonymous,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContributionStatus = `-- name: UpdateContributionStatus :exec
UPDATE contributions SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateContributionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateContributionStatus(ctx context.Context, arg UpdateContributionStatusParams) error {
	_, err := q.db.Exec(ctx, updateContributionStatus, arg.ID, arg.Status)
	return err
}
