// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (organization_id, kind, storage_key, mime_type, size_bytes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, kind, storage_key, mime_type, size_bytes, created_at
`

type CreateFileParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Kind           string    `json:"kind"`
	StorageKey     string    `json:"storage_key"`
	MimeType       string    `json:"mime_type"`
	SizeBytes      int64     `json:"size_bytes"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.OrganizationID,
		arg.Kind,
		arg.StorageKey,
		arg.MimeType,
		arg.SizeBytes,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, organization_id, kind, storage_key, mime_type, size_bytes, created_at FROM files WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}
