// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID             uuid.UUID          `json:"id"`
	ActorUserID    pgtype.UUID        `json:"actor_user_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Action         string             `json:"action"`
	EntityType     string             `json:"entity_type"`
	EntityID       uuid.UUID          `json:"entity_id"`
	Data           []byte             `json:"data"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Campaign struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	TypeKey        string             `json:"type_key"`
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	Description    string             `json:"description"`
	CoverFileID    pgtype.UUID        `json:"cover_file_id"`
	GoalAmount     pgtype.Int8        `json:"goal_amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	Settings       []byte             `json:"settings"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CampaignImage struct {
	ID         uuid.UUID          `json:"id"`
	CampaignID uuid.UUID          `json:"campaign_id"`
	FileID     uuid.UUID          `json:"file_id"`
	Position   int32              `json:"position"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CampaignTotal struct {
	CampaignID       uuid.UUID `json:"campaign_id"`
	RaisedGross      int32     `json:"raised_gross"`
	RaisedNetApprox  int32     `json:"raised_net_approx"`
	ContributorCount int64     `json:"contributor_count"`
}

type Contribution struct {
	ID            uuid.UUID          `json:"id"`
	CampaignID    uuid.UUID          `json:"campaign_id"`
	ContributorID uuid.UUID          `json:"contributor_id"`
	Amount        int64              `json:"amount"`
	Currency      string             `json:"currency"`
	IsAnonymous   bool               `json:"is_anonymous"`
	Message       pgtype.Text        `json:"message"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Contributor struct {
	ID        uuid.UUID          `json:"id"`
	FullName  string             `json:"full_name"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type File struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Kind           string             `json:"kind"`
	StorageKey     string             `json:"storage_key"`
	MimeType       string             `json:"mime_type"`
	SizeBytes      int64              `json:"size_bytes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID                  uuid.UUID          `json:"id"`
	Name                string             `json:"name"`
	Kind                string             `json:"kind"`
	CommissionRate      pgtype.Numeric     `json:"commission_rate"`
	Rut                 pgtype.Text        `json:"rut"`
	PayoutBank          pgtype.Text        `json:"payout_bank"`
	PayoutAccountType   pgtype.Text        `json:"payout_account_type"`
	PayoutAccountNumber pgtype.Text        `json:"payout_account_number"`
	PayoutHolderName    pgtype.Text        `json:"payout_holder_name"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMember struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID                    uuid.UUID          `json:"id"`
	ContributionID        uuid.UUID          `json:"contribution_id"`
	IdempotencyKey        string             `json:"idempotency_key"`
	Provider              string             `json:"provider"`
	ProviderRef           pgtype.Text        `json:"provider_ref"`
	Status                string             `json:"status"`
	AmountGross           int64              `json:"amount_gross"`
	CommissionRateApplied pgtype.Numeric     `json:"commission_rate_applied"`
	CommissionAmount      int64              `json:"commission_amount"`
	AmountNet             int64              `json:"amount_net"`
	Currency              string             `json:"currency"`
	PayeeSnapshot         []byte             `json:"payee_snapshot"`
	ConfirmedAt           pgtype.Timestamptz `json:"confirmed_at"`
	FailedAt              pgtype.Timestamptz `json:"failed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type PaymentRefund struct {
	ID          uuid.UUID          `json:"id"`
	PaymentID   uuid.UUID          `json:"payment_id"`
	Amount      int64              `json:"amount"`
	ProviderRef pgtype.Text        `json:"provider_ref"`
	Reason      pgtype.Text        `json:"reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	FullName        string             `json:"full_name"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserIdentity struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Provider        string             `json:"provider"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	ProviderSubject pgtype.Text        `json:"provider_subject"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
