// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOrganizationMember = `-- name: CreateOrganizationMember :exec
INSERT INTO organization_members (organization_id, user_id, role)
VALUES ($1, $2, $3)
`

type CreateOrganizationMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, createOrganizationMember, arg.OrganizationID, arg.UserID, arg.Role)
	return err
}
