// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, kind)
VALUES ($1, 'personal')
RETURNING id, name, kind, commission_rate, rut, payout_bank, payout_account_type, payout_account_number, payout_holder_name, created_at, updated_at
`

func (q *Queries) CreateOrganization(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CommissionRate,
		&i.Rut,
		&i.PayoutBank,
		&i.PayoutAccountType,
		&i.PayoutAccountNumber,
		&i.PayoutHolderName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, kind, commission_rate, rut, payout_bank, payout_account_type, payout_account_number, payout_holder_name, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CommissionRate,
		&i.Rut,
		&i.PayoutBank,
		&i.PayoutAccountType,
		&i.PayoutAccountNumber,
		&i.PayoutHolderName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonalOrganizationByUserID = `-- name: GetPersonalOrganizationByUserID :one
SELECT o.id, o.name, o.kind, o.commission_rate, o.rut, o.payout_bank, o.payout_account_type, o.payout_account_number, o.payout_holder_name, o.created_at, o.updated_at FROM organizations o
JOIN organization_members om ON om.organization_id = o.id
WHERE om.user_id = $1 AND o.kind = 'personal'
LIMIT 1
`

func (q *Queries) GetPersonalOrganizationByUserID(ctx context.Context, userID uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getPersonalOrganizationByUserID, userID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CommissionRate,
		&i.Rut,
		&i.PayoutBank,
		&i.PayoutAccountType,
		&i.PayoutAccountNumber,
		&i.PayoutHolderName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationOwnerByOrgID = `-- name: GetOrganizationOwnerByOrgID :one
SELECT u.email, u.full_name, u.email_verified_at FROM users u
JOIN organization_members om ON om.user_id = u.id
WHERE om.organization_id = $1 AND om.role = 'owner'
LIMIT 1
`

type GetOrganizationOwnerByOrgIDRow struct {
	Email           string             `json:"email"`
	FullName        string             `json:"full_name"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

func (q *Queries) GetOrganizationOwnerByOrgID(ctx context.Context, organizationID uuid.UUID) (GetOrganizationOwnerByOrgIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationOwnerByOrgID, organizationID)
	var i GetOrganizationOwnerByOrgIDRow
	err := row.Scan(&i.Email, &i.FullName, &i.EmailVerifiedAt)
	return i, err
}
