// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_refunds.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentRefund = `-- name: CreatePaymentRefund :one
INSERT INTO payment_refunds (payment_id, amount, provider_ref, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, payment_id, amount, provider_ref, reason, created_at
`

type CreatePaymentRefundParams struct {
	PaymentID   uuid.UUID   `json:"payment_id"`
	Amount      int64       `json:"amount"`
	ProviderRef pgtype.Text `json:"provider_ref"`
	Reason      pgtype.Text `json:"reason"`
}

func (q *Queries) CreatePaymentRefund(ctx context.Context, arg CreatePaymentRefundParams) (PaymentRefund, error) {
	row := q.db.QueryRow(ctx, createPaymentRefund,
		arg.PaymentID,
		arg.Amount,
		arg.ProviderRef,
		arg.Reason,
	)
	var i PaymentRefund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Amount,
		&i.ProviderRef,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getRefundedAmountByPaymentID = `-- name: GetRefundedAmountByPaymentID :one
SELECT COALESCE(SUM(amount), 0)::bigint FROM payment_refunds WHERE payment_id = $1
`

func (q *Queries) GetRefundedAmountByPaymentID(ctx context.Context, paymentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getRefundedAmountByPaymentID, paymentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
