// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
  contribution_id, idempotency_key, provider, provider_ref, status,
  amount_gross, commission_rate_applied, commission_amount, amount_net, payee_snapshot
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, contribution_id, idempotency_key, provider, provider_ref, status, amount_gross, commission_rate_applied, commission_amount, amount_net, currency, payee_snapshot, confirmed_at, failed_at, created_at, updated_at
`

type CreatePaymentParams struct {
	ContributionID        uuid.UUID      `json:"contribution_id"`
	IdempotencyKey        string         `json:"idempotency_key"`
	Provider              string         `json:"provider"`
	ProviderRef           pgtype.Text    `json:"provider_ref"`
	Status                string         `json:"status"`
	AmountGross           int64          `json:"amount_gross"`
	CommissionRateApplied pgtype.Numeric `json:"commission_rate_applied"`
	CommissionAmount      int64          `json:"commission_amount"`
	AmountNet             int64          `json:"amount_net"`
	PayeeSnapshot         []byte         `json:"payee_snapshot"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ContributionID,
		arg.IdempotencyKey,
		arg.Provider,
		arg.ProviderRef,
		arg.Status,
		arg.AmountGross,
		arg.CommissionRateApplied,
		arg.CommissionAmount,
		arg.AmountNet,
		arg.PayeeSnapshot,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ContributionID,
		&i.IdempotencyKey,
		&i.Provider,
		&i.ProviderRef,
		&i.Status,
		&i.AmountGross,
		&i.CommissionRateApplied,
		&i.CommissionAmount,
		&i.AmountNet,
		&i.Currency,
		&i.PayeeSnapshot,
		&i.ConfirmedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByContributionID = `-- name: GetPaymentByContributionID :one
SELECT id, contribution_id, idempotency_key, provider, provider_ref, status, amount_gross, commission_rate_applied, commission_amount, amount_net, currency, payee_snapshot, confirmed_at, failed_at, created_at, updated_at FROM payments WHERE contribution_id = $1
`

func (q *Queries) GetPaymentByContributionID(ctx context.Context, contributionID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByContributionID, contributionID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ContributionID,
		&i.IdempotencyKey,
		&i.Provider,
		&i.ProviderRef,
		&i.Status,
		&i.AmountGross,
		&i.CommissionRateApplied,
		&i.CommissionAmount,
		&i.AmountNet,
		&i.Currency,
		&i.PayeeSnapshot,
		&i.ConfirmedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, contribution_id, idempotency_key, provider, provider_ref, status, amount_gross, commission_rate_applied, commission_amount, amount_net, currency, payee_snapshot, confirmed_at, failed_at, created_at, updated_at FROM payments WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ContributionID,
		&i.IdempotencyKey,
		&i.Provider,
		&i.ProviderRef,
		&i.Status,
		&i.AmountGross,
		&i.CommissionRateApplied,
		&i.CommissionAmount,
		&i.AmountNet,
		&i.Currency,
		&i.PayeeSnapshot,
		&i.ConfirmedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByProviderRefForUpdate = `-- name: GetPaymentByProviderRefForUpdate :one
SELECT id, contribution_id, idempotency_key, provider, provider_ref, status, amount_gross, commission_rate_applied, commission_amount, amount_net, currency, payee_snapshot, confirmed_at, failed_at, created_at, updated_at FROM payments WHERE provider = $1 AND provider_ref = $2 FOR UPDATE
`

type GetPaymentByProviderRefForUpdateParams struct {
	Provider    string      `json:"provider"`
	ProviderRef pgtype.Text `json:"provider_ref"`
}

func (q *Queries) GetPaymentByProviderRefForUpdate(ctx context.Context, arg GetPaymentByProviderRefForUpdateParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderRefForUpdate, arg.Provider, arg.ProviderRef)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ContributionID,
		&i.IdempotencyKey,
		&i.Provider,
		&i.ProviderRef,
		&i.Status,
		&i.AmountGross,
		&i.CommissionRateApplied,
		&i.CommissionAmount,
		&i.AmountNet,
		&i.Currency,
		&i.PayeeSnapshot,
		&i.ConfirmedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIDForUpdate = `-- name: GetPaymentByIDForUpdate :one
SELECT id, contribution_id, idempotency_key, provider, provider_ref, status, amount_gross, commission_rate_applied, commission_amount, amount_net, currency, payee_snapshot, confirmed_at, failed_at, created_at, updated_at FROM payments WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetPaymentByIDForUpdate(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIDForUpdate, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ContributionID,
		&i.IdempotencyKey,
		&i.Provider,
		&i.ProviderRef,
		&i.Status,
		&i.AmountGross,
		&i.CommissionRateApplied,
		&i.CommissionAmount,
		&i.AmountNet,
		&i.Currency,
		&i.PayeeSnapshot,
		&i.ConfirmedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments SET status = $2, confirmed_at = $3, failed_at = $4, updated_at = now()
WHERE id = $1
RETURNING id, contribution_id, idempotency_key, provider, provider_ref, status, amount_gross, commission_rate_applied, commission_amount, amount_net, currency, payee_snapshot, confirmed_at, failed_at, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID          uuid.UUID          `json:"id"`
	Status      string             `json:"status"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
	FailedAt    pgtype.Timestamptz `json:"failed_at"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus,
		arg.ID,
		arg.Status,
		arg.ConfirmedAt,
		arg.FailedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ContributionID,
		&i.IdempotencyKey,
		&i.Provider,
		&i.ProviderRef,
		&i.Status,
		&i.AmountGross,
		&i.CommissionRateApplied,
		&i.CommissionAmount,
		&i.AmountNet,
		&i.Currency,
		&i.PayeeSnapshot,
		&i.ConfirmedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
