// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payouts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayout = `-- name: CreatePayout :one
INSERT INTO payouts (organization_id, amount, note, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, amount, note, created_by, created_at
`

type CreatePayoutParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Amount         int64       `json:"amount"`
	Note           pgtype.Text `json:"note"`
	CreatedBy      uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error) {
	row := q.db.QueryRow(ctx, createPayout,
		arg.OrganizationID,
		arg.Amount,
		arg.Note,
		arg.CreatedBy,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Amount,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingPayouts = `-- name: ListPendingPayouts :many
SELECT
  o.id AS organization_id,
  o.name AS organization_name,
  o.rut,
  o.payout_bank,
  o.payout_account_type,
  o.payout_account_number,
  o.payout_holder_name,
  COALESCE(eligible.amount, 0)::bigint AS eligible_net,
  COALESCE(paid.amount, 0)::bigint AS total_paid,
  (COALESCE(eligible.amount, 0) - COALESCE(paid.amount, 0))::bigint AS pending_amount
FROM organizations o
LEFT JOIN LATERAL (
  SELECT SUM(p.amount_net - COALESCE(r.refunded, 0)) AS amount
  FROM campaigns c
  JOIN contributions ct ON ct.campaign_id = c.id
  JOIN payments p ON p.contribution_id = ct.id
  LEFT JOIN LATERAL (
    SELECT SUM(pr.amount) AS refunded FROM payment_refunds pr WHERE pr.payment_id = p.id
  ) r ON true
  WHERE c.organization_id = o.id
    AND p.status IN ('confirmed', 'partially_refunded')
    AND p.confirmed_at <= now() - make_interval(days => $1::int)
) eligible ON true
LEFT JOIN LATERAL (
  SELECT SUM(amount) AS amount FROM payouts WHERE organization_id = o.id
) paid ON true
WHERE COALESCE(eligible.amount, 0) - COALESCE(paid.amount, 0) > 0
ORDER BY o.name
LIMIT $2 OFFSET $3
`

type ListPendingPayoutsParams struct {
	HoldDays int32 `json:"hold_days"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type ListPendingPayoutsRow struct {
	OrganizationID      uuid.UUID   `json:"organization_id"`
	OrganizationName    string      `json:"organization_name"`
	Rut                 pgtype.Text `json:"rut"`
	PayoutBank          pgtype.Text `json:"payout_bank"`
	PayoutAccountType   pgtype.Text `json:"payout_account_type"`
	PayoutAccountNumber pgtype.Text `json:"payout_account_number"`
	PayoutHolderName    pgtype.Text `json:"payout_holder_name"`
	EligibleNet         int64       `json:"eligible_net"`
	TotalPaid           int64       `json:"total_paid"`
	PendingAmount       int64       `json:"pending_amount"`
}

func (q *Queries) ListPendingPayouts(ctx context.Context, arg ListPendingPayoutsParams) ([]ListPendingPayoutsRow, error) {
	rows, err := q.db.Query(ctx, listPendingPayouts, arg.HoldDays, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingPayoutsRow
	for rows.Next() {
		var i ListPendingPayoutsRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.OrganizationName,
			&i.Rut,
			&i.PayoutBank,
			&i.PayoutAccountType,
			&i.PayoutAccountNumber,
			&i.PayoutHolderName,
			&i.EligibleNet,
			&i.TotalPaid,
			&i.PendingAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutsByOrg = `-- name: ListPayoutsByOrg :many
SELECT id, organization_id, amount, note, created_by, created_at FROM payouts WHERE organization_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPayoutsByOrgParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListPayoutsByOrg(ctx context.Context, arg ListPayoutsByOrgParams) ([]Payout, error) {
	rows, err := q.db.Query(ctx, listPayoutsByOrg, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payout
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Amount,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
