// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	CreateCampaignImage(ctx context.Context, arg CreateCampaignImageParams) (CampaignImage, error)
	CreateContribution(ctx context.Context, arg CreateContributionParams) (Contribution, error)
	CreateContributor(ctx context.Context, arg CreateContributorParams) (Contributor, error)
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) error
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateOrganization(ctx context.Context, name string) (Organization, error)
	CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) error
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePaymentRefund(ctx context.Context, arg CreatePaymentRefundParams) (PaymentRefund, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (UserIdentity, error)
	DeleteCampaignImage(ctx context.Context, arg DeleteCampaignImageParams) (int64, error)
	GetAdminMetrics(ctx context.Context) (GetAdminMetricsRow, error)
	GetCampaignByID(ctx context.Context, id uuid.UUID) (Campaign, error)
	GetCampaignByIDForOrg(ctx context.Context, arg GetCampaignByIDForOrgParams) (Campaign, error)
	GetCampaignBySlug(ctx context.Context, slug string) (Campaign, error)
	GetCampaignTotals(ctx context.Context, campaignID uuid.UUID) (CampaignTotal, error)
	GetContributionByID(ctx context.Context, id uuid.UUID) (Contribution, error)
	GetFeaturedCampaign(ctx context.Context) (Campaign, error)
	GetContributorByID(ctx context.Context, id uuid.UUID) (Contributor, error)
	GetFileByID(ctx context.Context, id uuid.UUID) (File, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationOwnerByOrgID(ctx context.Context, organizationID uuid.UUID) (GetOrganizationOwnerByOrgIDRow, error)
	GetPasswordIdentityByUserID(ctx context.Context, userID uuid.UUID) (UserIdentity, error)
	GetPaymentByContributionID(ctx context.Context, contributionID uuid.UUID) (Payment, error)
	GetPaymentByIDForUpdate(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error)
	GetPaymentByProviderRefForUpdate(ctx context.Context, arg GetPaymentByProviderRefForUpdateParams) (Payment, error)
	GetPersonalOrganizationByUserID(ctx context.Context, userID uuid.UUID) (Organization, error)
	GetRefundedAmountByPaymentID(ctx context.Context, paymentID uuid.UUID) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetValidEmailVerificationTokenByHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error)
	GetValidPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetValidRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	ListActiveCampaigns(ctx context.Context, arg ListActiveCampaignsParams) ([]Campaign, error)
	ListAdminCampaigns(ctx context.Context, arg ListAdminCampaignsParams) ([]ListAdminCampaignsRow, error)
	ListAdminPayments(ctx context.Context, arg ListAdminPaymentsParams) ([]ListAdminPaymentsRow, error)
	ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]ListAdminUsersRow, error)
	ListCampaignImages(ctx context.Context, campaignID uuid.UUID) ([]ListCampaignImagesRow, error)
	ListCampaignsByOrg(ctx context.Context, arg ListCampaignsByOrgParams) ([]Campaign, error)
	ListContributionsByCampaign(ctx context.Context, arg ListContributionsByCampaignParams) ([]Contribution, error)
	ListParticipantsByCampaign(ctx context.Context, arg ListParticipantsByCampaignParams) ([]ListParticipantsByCampaignRow, error)
	ListParticipantsByCampaignFiltered(ctx context.Context, arg ListParticipantsByCampaignFilteredParams) ([]ListParticipantsByCampaignFilteredRow, error)
	MarkEmailVerificationTokenUsed(ctx context.Context, tokenHash string) error
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
	MarkPasswordResetTokenUsed(ctx context.Context, tokenHash string) error
	NextCampaignImagePosition(ctx context.Context, campaignID uuid.UUID) (int32, error)
	PublishDueCampaigns(ctx context.Context) ([]Campaign, error)
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	SlugExists(ctx context.Context, slug string) (bool, error)
	SoftDeleteCampaign(ctx context.Context, id uuid.UUID) error
	UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error)
	UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error)
	UpdateCampaignImagePosition(ctx context.Context, arg UpdateCampaignImagePositionParams) (int64, error)
	UpdateContributionStatus(ctx context.Context, arg UpdateContributionStatusParams) error
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdatePaymentStatusOnly(ctx context.Context, arg UpdatePaymentStatusOnlyParams) (Payment, error)
}

var _ Querier = (*Queries)(nil)
