// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_identities.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserIdentity = `-- name: CreateUserIdentity :one
INSERT INTO user_identities (user_id, provider, password_hash)
VALUES ($1, 'password', $2)
RETURNING id, user_id, provider, password_hash, provider_subject, created_at
`

type CreateUserIdentityParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, createUserIdentity, arg.UserID, arg.PasswordHash)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.PasswordHash,
		&i.ProviderSubject,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordIdentityByUserID = `-- name: GetPasswordIdentityByUserID :one
SELECT id, user_id, provider, password_hash, provider_subject, created_at FROM user_identities WHERE user_id = $1 AND provider = 'password'
`

func (q *Queries) GetPasswordIdentityByUserID(ctx context.Context, userID uuid.UUID) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getPasswordIdentityByUserID, userID)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.PasswordHash,
		&i.ProviderSubject,
		&i.CreatedAt,
	)
	return i, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE user_identities SET password_hash = $2 WHERE user_id = $1 AND provider = 'password'
`

type UpdatePasswordHashParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.UserID, arg.PasswordHash)
	return err
}
